services:
  discord-bot:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      LAVALINK_HOST: NODE
    depends_on:
      - NODE
    volumes:
      - lauffy-data:/app/data

  NODE:
    build:
      context: .
      dockerfile: Dockerfile.nodelink
    image: lauffy-nodelink:local
    restart: unless-stopped
    environment:
      NODELINK_SERVER_PASSWORD: ${LAVALINK_PASS:-youshallnotpass}

#  lavalink:
#    build:
#      context: .
#      dockerfile: Dockerfile.lavalink
#    image: lauffy-lavalink:local
#    restart: unless-stopped
#    environment:
#      LAVALINK_SERVER_PASSWORD: ${LAVALINK_PASS:-youshallnotpass}
#    volumes:
#      - ./application.yml:/opt/Lavalink/application.yml:ro

volumes:
  lauffy-data:
